import React from 'react';
import ReactDOM from 'react-dom';

import Template from '../mainTemplate';
import MuiThemeProvider from '@material-ui/core/styles/MuiThemeProvider';

class Home extends React.Component {
    render() {
        return (
            <div style={{color:'black'}}>
                <h1> This should be my test content </h1>
                <h1> This should be my test content </h1>
                <h1> This should be my test content </h1>
                <h1> This should be my test content </h1>
                <h1> This should be my test content </h1>
                <p> Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ...... Maybe I should just ......Maybe I should just ......
                </p>
                <h1> This should be my test content </h1>
                <p> Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ...... Maybe I should just ......Maybe I should just ......
                </p>
                <h1> This should be my test content </h1>
                <p> Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ...... Maybe I should just ......Maybe I should just ......
                </p>
                <h1> This should be my test content </h1>
                <p> Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ......
                    Maybe I should just ...... Maybe I should just ...... Maybe I should just ...... Maybe I should just ......Maybe I should just ......
                </p>
            </div>
        );
    }
}

ReactDOM.render(<Template content={<Home />}/>, document.getElementById('importContent'));
